//<auto-generated/>
namespace AnyTrack.Backend.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddedCompletedDatetoSprintStory : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.SprintStories", "DateCompleted", c => c.DateTime());
        }
        
        public override void Down()
        {
            DropColumn("dbo.SprintStories", "DateCompleted");
        }
    }
}
