// <auto-generated />
namespace AnyTrack.Backend.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Addingresetquestionsandskillstouser : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Users", "SecretQuestion", c => c.String());
            AddColumn("dbo.Users", "SecretAnswer", c => c.String());
            AddColumn("dbo.Users", "Skills", c => c.String());
        }
        
        public override void Down()
        {
            DropColumn("dbo.Users", "Skills");
            DropColumn("dbo.Users", "SecretAnswer");
            DropColumn("dbo.Users", "SecretQuestion");
        }
    }
}
