// <auto-generated />
namespace AnyTrack.Backend.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Addingtasksandtaskhours : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Tasks",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        ConditionsOfSatisfaction = c.String(),
                        Summary = c.String(),
                        Description = c.String(),
                        Blocked = c.Boolean(nullable: false),
                        Updated = c.DateTime(),
                        Created = c.DateTime(),
                        Assignee_Id = c.Guid(),
                        SprintStory_Id = c.Guid(),
                        Tester_Id = c.Guid(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Users", t => t.Assignee_Id)
                .ForeignKey("dbo.SprintStories", t => t.SprintStory_Id)
                .ForeignKey("dbo.Users", t => t.Tester_Id)
                .Index(t => t.Assignee_Id)
                .Index(t => t.SprintStory_Id)
                .Index(t => t.Tester_Id);
            
            CreateTable(
                "dbo.TaskHourEstimates",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        Estimate = c.Double(nullable: false),
                        Updated = c.DateTime(),
                        Created = c.DateTime(),
                        Task_Id = c.Guid(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Tasks", t => t.Task_Id)
                .Index(t => t.Task_Id);
            
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Tasks", "Tester_Id", "dbo.Users");
            DropForeignKey("dbo.TaskHourEstimates", "Task_Id", "dbo.Tasks");
            DropForeignKey("dbo.Tasks", "SprintStory_Id", "dbo.SprintStories");
            DropForeignKey("dbo.Tasks", "Assignee_Id", "dbo.Users");
            DropIndex("dbo.TaskHourEstimates", new[] { "Task_Id" });
            DropIndex("dbo.Tasks", new[] { "Tester_Id" });
            DropIndex("dbo.Tasks", new[] { "SprintStory_Id" });
            DropIndex("dbo.Tasks", new[] { "Assignee_Id" });
            DropTable("dbo.TaskHourEstimates");
            DropTable("dbo.Tasks");
        }
    }
}
