// <auto-generated />
namespace AnyTrack.Backend.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddingProject : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Projects",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        Name = c.String(),
                        Description = c.String(),
                        VersionControl = c.String(),
                        StartedOn = c.DateTime(nullable: false),
                        Updated = c.DateTime(),
                        Created = c.DateTime(),
                        ProductOwner_Id = c.Guid(),
                        ProjectManager_Id = c.Guid(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Users", t => t.ProductOwner_Id)
                .ForeignKey("dbo.Users", t => t.ProjectManager_Id)
                .Index(t => t.ProductOwner_Id)
                .Index(t => t.ProjectManager_Id);
            
            AddColumn("dbo.Users", "Project_Id", c => c.Guid());
            CreateIndex("dbo.Users", "Project_Id");
            AddForeignKey("dbo.Users", "Project_Id", "dbo.Projects", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Users", "Project_Id", "dbo.Projects");
            DropForeignKey("dbo.Projects", "ProjectManager_Id", "dbo.Users");
            DropForeignKey("dbo.Projects", "ProductOwner_Id", "dbo.Users");
            DropIndex("dbo.Users", new[] { "Project_Id" });
            DropIndex("dbo.Projects", new[] { "ProjectManager_Id" });
            DropIndex("dbo.Projects", new[] { "ProductOwner_Id" });
            DropColumn("dbo.Users", "Project_Id");
            DropTable("dbo.Projects");
        }
    }
}
