// <auto-generated />
namespace AnyTrack.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingmigrationtocoverT1andT2changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingmigrationtocoverT1andT2changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201510282334577_Adding migration to cover T1 and T2 changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
