// <auto-generated />
namespace AnyTrack.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingbooleantoastoryInSprint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingbooleantoastoryInSprint));
        
        string IMigrationMetadata.Id
        {
            get { return "201512010554304_Adding boolean to a story (InSprint)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
