// <auto-generated />
namespace AnyTrack.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Configuringprojectstousersasmanymanyforscrummasters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Configuringprojectstousersasmanymanyforscrummasters));
        
        string IMigrationMetadata.Id
        {
            get { return "201511061057447_Configuring projects to users as many-many for scrum masters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
