// <auto-generated />
namespace AnyTrack.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Createdamanytomanyrelationshipbetweenuserandsprint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Createdamanytomanyrelationshipbetweenuserandsprint));
        
        string IMigrationMetadata.Id
        {
            get { return "201511302109142_Created a many to many relationship between user and sprint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
