//<auto-generated/>
namespace AnyTrack.Backend.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddingbooleantoastoryInSprint : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Stories", "InSprint", c => c.Boolean(nullable: false));
        }
        
        public override void Down()
        {
            DropColumn("dbo.Stories", "InSprint");
        }
    }
}
