// <auto-generated />
namespace AnyTrack.Backend.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Extrafieldonstorymodelforstorycreation : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Stories", "AsA", c => c.String());
            AddColumn("dbo.Stories", "IWant", c => c.String());
            AddColumn("dbo.Stories", "SoThat", c => c.String());
            DropColumn("dbo.Stories", "StoryName");
            DropColumn("dbo.Stories", "StoryBreakdown");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Stories", "StoryBreakdown", c => c.String());
            AddColumn("dbo.Stories", "StoryName", c => c.String());
            DropColumn("dbo.Stories", "SoThat");
            DropColumn("dbo.Stories", "IWant");
            DropColumn("dbo.Stories", "AsA");
        }
    }
}
