// <auto-generated />
namespace AnyTrack.Backend.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Makingdatesnullable : DbMigration
    {
        public override void Up()
        {
            AlterColumn("dbo.Users", "Updated", c => c.DateTime());
            AlterColumn("dbo.Users", "Created", c => c.DateTime());
        }
        
        public override void Down()
        {
            AlterColumn("dbo.Users", "Created", c => c.DateTime(nullable: false));
            AlterColumn("dbo.Users", "Updated", c => c.DateTime(nullable: false));
        }
    }
}
