// <auto-generated />
namespace AnyTrack.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Correctingsprintteamrelationshipandaddingscrummastertosprint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Correctingsprintteamrelationshipandaddingscrummastertosprint));
        
        string IMigrationMetadata.Id
        {
            get { return "201511301844289_Correcting sprint team relationship and adding scrum master to sprint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
