// <auto-generated />
namespace AnyTrack.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingmigrationfollowingT17merge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingmigrationfollowingT17merge));
        
        string IMigrationMetadata.Id
        {
            get { return "201512040222451_Adding migration following T17 merge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
