// <auto-generated/>
namespace AnyTrack.Backend.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Changetotask : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.UpdatedHours", "Task_Id", "dbo.Tasks");
            DropIndex("dbo.UpdatedHours", new[] { "Task_Id" });
            CreateTable(
                "dbo.TaskHourEstimates",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        Estimate = c.Double(nullable: false),
                        Updated = c.DateTime(),
                        Created = c.DateTime(),
                        Task_Id = c.Guid(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Tasks", t => t.Task_Id)
                .Index(t => t.Task_Id);
            
            DropColumn("dbo.Tasks", "HoursRemaining");
            DropTable("dbo.UpdatedHours");
        }
        
        public override void Down()
        {
            CreateTable(
                "dbo.UpdatedHours",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        NewEstimate = c.Double(nullable: false),
                        LogEstimate = c.Double(nullable: false),
                        Updated = c.DateTime(),
                        Created = c.DateTime(),
                        Task_Id = c.Guid(),
                    })
                .PrimaryKey(t => t.Id);
            
            AddColumn("dbo.Tasks", "HoursRemaining", c => c.Double(nullable: false));
            DropForeignKey("dbo.TaskHourEstimates", "Task_Id", "dbo.Tasks");
            DropIndex("dbo.TaskHourEstimates", new[] { "Task_Id" });
            DropTable("dbo.TaskHourEstimates");
            CreateIndex("dbo.UpdatedHours", "Task_Id");
            AddForeignKey("dbo.UpdatedHours", "Task_Id", "dbo.Tasks", "Id");
        }
    }
}
