// <auto-generated />
namespace AnyTrack.Backend.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Addingstory : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.Stories",
                c => new
                    {
                        Id = c.Guid(nullable: false),
                        StoryName = c.String(),
                        Description = c.String(),
                        Summary = c.String(),
                        Assignee = c.String(),
                        Tester = c.String(),
                        ConditionsOfSatisfaction = c.String(),
                        Updated = c.DateTime(),
                        Created = c.DateTime(),
                        Project_Id = c.Guid(),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Projects", t => t.Project_Id)
                .Index(t => t.Project_Id);
            
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Stories", "Project_Id", "dbo.Projects");
            DropIndex("dbo.Stories", new[] { "Project_Id" });
            DropTable("dbo.Stories");
        }
    }
}
