// <auto-generated />
namespace AnyTrack.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addingmigrationtomergethelastfewafteranissue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingmigrationtomergethelastfewafteranissue));
        
        string IMigrationMetadata.Id
        {
            get { return "201512020048275_Adding migration to merge the last few after an issue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
